### ISSUE TITLE
MonthView and select region for new appointment

### ISSUE THREAD

**Issue by ronnyek** [gservera/ScheduleKit#5]
Questions, not so much bugs...

I'm just asking... is there currently a monthview that I can use, (maybe gridview?)

Also, what about the ability to highly an empty region of the schedule component to be able to create a new appointment with the specfied start and end times?

**Comment by gservera** [comment]
Hi @ronnyek. Sorry for the late response!

No, there's currently no month view available (maybe in the future! please feel free to make a pull request if you succeed in making one). I can't promise much more on that since I haven't much time to code now.

Anyway, the idea of creating an appointment by clicking and dragging on an empty region sounds great, I'll see what I can do on that!

Thank you for your interest and I hope you enjoy using this (little) project.
